### ISSUE TITLE
Todo 기능 구현

### ISSUE THREAD

**Issue by Aroma-oh** [Aroma-oh/SRP-DIP-OCP#2]
# Description
### Todo
* **Todo component**: UI, UI 연관 상태 관리만을 담당한다. 
* **TodoContext**: Todo 컴포넌트에서 필요한 상태와 함수를 Povider를 통해 전달한다. 
* **TodoService**: API 호출에 필요한 기능을 제공한다. 

#### TodoService
* **get() : `Promise<Todo[]>`**
* **create(todo: string): `Promise<Todo>`**

#### TodoContext
* todos: `Promise<Todo[]>`;
* createTodo: (todo: string) => `Promise<void>`;
---

# Task
#### Todo component
- [x] Todo 목록과, 새로운 Todo 입력을 받는 UI를 생성한다. 
#### TodoService
- [x] Todo 목록 가져오기 및 생성 기능을 구현한다. 
- [x] 기능 구현은 Interface를 따른다.
